Code/James/django/labs/rps/urls.py
from django.urls import path
from . import views

app_name = 'rps'
urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),
]

Code/James/django/labs/rps/views.py
from django.shortcuts import render
import random

# Create your views here.
def index(request):
    return render(request, 'rps/index.html')

def result(request):
    choice=request.GET['choice']
    computer = random.choice(['rock', 'paper', 'scissors'])
    result = ''
    if choice == computer:
        result = 'You tied'
    elif choice == 'rock':
        if computer == 'paper':
            result = "You lost."
        else:
            result = "You won!"
    elif choice == 'paper':
        if computer == 'scissors':
            result = "You lost."
        else:
            result = "You won!"
    elif choice == 'scissors':
        if computer == 'rock':
            result = "You lost."
        else:
            result = "You won!"
    return render(request, 'rps/results.html', {
        'result': result
        })

Code/James/django/labs/rps/templates/rps/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rock Paper Scissors</title>
    <link rel="stylesheet" href ="{% static 'rps/style.css' %}">
</head>
<body>
    <h1>Welcome to Rock Paper Scissors</h1>
    <h3>Pick one:</h3>
    <div class ='buttons'>
        <a href = '{% url "rps:result" %}?choice=rock'>Rock</a>
        <a href = '{% url "rps:result" %}?choice=paper'>Paper</a>
        <a href = '{% url "rps:result" %}?choice=scissors'>Scissors</a>
    </div>
</body>
</html>

Code/James/django/labs/rps/templates/rps/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{ result }}</h2>
</body>
</html>