Code/James/django/labs/grocery_list/urls.py
from django.urls import path
from . import views

app_name = 'grocery_list'
urlpatterns = [
    path('', views.grocery_list, name='grocery_list'),
    path('grocery_list/', views.input, name='input'),
    path('buy/<int:item_id>/', views.buy_item, name='buy'),
    path('delete/<int:item_id>/', views.delete_item, name='delete'),
]

Code/James/django/labs/grocery_list/models.py
from django.db import models

class GroceryItem(models.Model):
    item = models.CharField(max_length=200)
    status = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.item} - {self.status}'

Code/James/django/labs/grocery_list/views.py
from typing import ItemsView
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import GroceryItem
from django.urls import reverse
from . import models

def grocery_list(request):
    grocery_list = models.GroceryItem.objects.all()
    return render(request, 'grocery_list/grocery_list.html', {'grocery_list':grocery_list})

def input(request):
    item_text = request.POST['item']
    new_item = models.GroceryItem()
    new_item.item = item_text
    new_item.save()
    print(request.POST)
    return HttpResponseRedirect(reverse('grocery_list:grocery_list'))

def buy_item(request, item_id):
    grocery_item = models.GroceryItem.objects.get(id=item_id)
    grocery_item.status = not grocery_item.status
    grocery_item.save()
    return HttpResponseRedirect(reverse('grocery_list:grocery_list')) #incomplete?

def delete_item(request, item_id):
    grocery_item = models.GroceryItem.objects.get(id=item_id)
    grocery_item.delete()
    return HttpResponseRedirect(reverse('grocery_list:grocery_list')) # index?

Code/James/django/labs/grocery_list/templates/grocery_list/grocery_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Groceries</title>
    <style>
        .status {
            text-decoration: line-through;
        }
    </style>
</head>
<body>
    <form action="{% url 'grocery_list:input' %}" method="post">
        {% csrf_token %}
        <input type="text" name="item">
        <button type="submit">Add item</button>
    </form>

    <ul>
        {% for grocery in grocery_list %}
        <li
        {% if grocery.status %}
        class="status"
        {% endif %}
        ><a href ="{% url 'grocery_list:buy' grocery.id %}">{{ grocery.item }}</a>
        <a href ="{% url 'grocery_list:delete' grocery.id %}">&times;</a>
        </li>
        {% endfor %}
      </ul>
</body>
</html>