Code/Derrick/Django/labs/blog/urls.py
from django.urls import path 
from . import views 

app_name = 'blog'

urlpatterns = [
    path('',views.register,name='index'),
    path('profile/',views.profile,name='profile'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.register,name='register'),
    path('edit/<int:post_id>',views.edit,name='edit'),
    path('create/',views.create,name='create'),
    path('posts/',views.posts,name='posts'),
    path('posts/<int:post_id>',views.details,name='details')

]

Code/Derrick/Django/labs/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=25)
    body = models.TextField(max_length=1000)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    public = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}, {self.body[:10]}, {self.user}, {self.public}, {self.date_created}'

Code/Derrick/Django/labs/blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import BlogPost

# from .models import BlogPost
# from django.forms.widgets import PasswordInput, Textarea

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=15, widget=forms.widgets.TextInput(attrs={'placeholder':'Username'}))
    email = forms.CharField(widget=forms.widgets.EmailInput(attrs={'placeholder':'Email'}))
    password = forms.CharField(max_length=15, widget=forms.widgets.PasswordInput(attrs={'placeholder':'Password'}))

class LoginForm(forms.Form):
    username = forms.CharField(max_length=15, widget=forms.widgets.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(max_length=15, widget=forms.widgets.PasswordInput(attrs={'placeholder':'Password'}))

class NewBlogPost(forms.Form):
    title = forms.CharField(max_length=25)
    body = forms.CharField(widget=forms.widgets.Textarea)

class EditBlogPost(forms.Form):
    title = forms.CharField(max_length=25)
    body = forms.CharField(widget=forms.widgets.Textarea)



         

Code/Derrick/Django/labs/blog/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import EditBlogPost, LoginForm, RegisterForm, NewBlogPost
from .models import BlogPost


# Create your views here.

def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request,'blog/register.html',{'form': form})

    elif request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(
                username = form.cleaned_data['username'],
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password']
            )
            
        return HttpResponseRedirect(reverse('blog:login'))

def user_login(request):
    if request.method == 'GET':
        return render(request,'blog/login.html',{'form': LoginForm()})

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user != None:
                login(request,user)
                return HttpResponseRedirect(reverse('blog:profile'))
                
            else:
                return render(request,'users/login.html')

@login_required
def profile(request):
    posts = BlogPost.objects.all().filter(user=request.user).order_by('date_created')
    return render(request,'blog/profile.html',{'posts': posts})
    
@login_required
def create(request):
    if request.method == 'GET':
        return render(request,'blog/create.html',{'form':NewBlogPost()})

    elif request.method == 'POST':
        form = NewBlogPost(request.POST)

        if form.is_valid():
            post = BlogPost()
            post.user = request.user
            post.title = form.cleaned_data['title']
            post.body = form.cleaned_data['body']
            post.save()

    return HttpResponseRedirect(reverse('blog:profile'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:login'))

@login_required
def edit(request,post_id):
    posts = BlogPost.objects.all().filter(id=post_id, user=request.user)
    post = posts.get(id=post_id)
    
    if request.method == 'POST':
        form = EditBlogPost(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.body = form.cleaned_data['body']
            post.save()
            return HttpResponseRedirect(reverse('blog:profile'))
    else:
        form = EditBlogPost({'title':post.title,'body':post.body}) # allows user to edit original post inside of the form
        return render(request,'blog/edit.html', {'form': form,'post': post, 'posts': posts})

@login_required
def posts(request):
    posts = BlogPost.objects.all()
    return render(request,'blog/posts.html',{'posts': posts})

@login_required
def details(request,post_id):
    post = BlogPost.objects.get(id=post_id)
    return render(request,'blog/details.html',{'post': post})

Code/Derrick/Django/labs/blog/templates/blog/_nav.html
<nav>
    <div class="logo">❤</div>
    <div class="nav_links">
        {% if not request.user.is_anonymous %}
            <a href="{% url 'blog:profile' %}">Profile</a>
            <a href="{% url 'blog:logout' %}">Logout</a>
            <a href="{% url 'blog:create' %}">New Blog Post</a>
            <a href="{% url 'blog:posts' %}">View All Posts</a>
        {% else %}
            <a href="{% url 'blog:register' %}">Register</a>
            <a href="{% url 'blog:login' %}">Login</a>
        {% endif %}
    </div>    
</nav>

Code/Derrick/Django/labs/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    {% block title_link %}{% endblock title_link %}
</head>
<body>
    {% include 'blog/_nav.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>     
</body>
</html>

Code/Derrick/Django/labs/blog/templates/blog/create.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>Create Post</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}

{% block content %}
<h3><span>{{ request.user }}</span> is creating a new post:</h3>
<form action="{% url 'blog:create' %}" method="post">
    <div class="form create">
        {% csrf_token %}
        {{ form }} 
        <button type="submit">Submit Post</button>
    </div>
</form>
{% endblock content %}   

Code/Derrick/Django/labs/blog/templates/blog/details.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>All Posts</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}

{% block content %}
<h3><span>{{ request.user }}</span> is viewing a post by <span>{{ post.user }}</span>:</h3>
<div class="post">
    <h1>{{ post.title }}</h1>
    <p>{{ post.body }}</p>
    <p class="author">Posted by <i><span>{{ post.user }}</span></i></p>
    {% if post.user == request.user %} 
        <a href="{% url 'blog:edit' post.id %}" class="button">Edit Post</a>
    {% endif %}
    <a href="{% url 'blog:posts' %}" class="button">Go Back</a>
</div>
{% endblock content %}

Code/Derrick/Django/labs/blog/templates/blog/edit.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>Edit Post</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}

{% block content %}
<h3><span>{{ request.user }}</span> is editing <span>{{ post.title }}</span>:</h3>
<form action="{% url 'blog:edit' post.id %}" method="post">
    <div class="form edit">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
    </div>
</form>
{% endblock content %}   

Code/Derrick/Django/labs/blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}

{% block content %}
<h1>Login Page</h1>
<div class="form-container">
    <form action="{% url 'blog:login' %}" method="post">
        <div class="form login">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Login</button>
            <p>Not a member yet? <a href="{% url 'blog:register' %}">Register here</a></p>
        </div>
    </form>
</div>
{% endblock content %}

Code/Derrick/Django/labs/blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>All Posts</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}

{% block content %}
<h3><span>{{ request.user }}</span> is viewing all posts:</h3>
{% for post in posts %}
<div class="post all">
    <a href="{% url 'blog:details' post.id %}"><h1>{{ post.title }}</h1></a>
    <p class="author">Posted by <i><span>{{ post.user }}</span></i></p>
</div>
{% endfor %}
{% endblock content %}

Code/Derrick/Django/labs/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>{{ request.user }}'s Profile</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}
    
{% block content %}
<h1>Welcome, {{ request.user }}</h1>
<a href="{% url 'blog:create' %}">Create New Post</a>   
<div class="posts">
    {% for post in posts %}
        <div class="post profile-post">
            <h1>{{ post.title }}</h1>
            <a href="{% url 'blog:details' post.id %}" class="button">View Post</a>
            <a href="{% url 'blog:edit' post.id %}" class="button">Edit Post</a>
        </div>
    {% endfor %}
</div>
{% endblock content %}

Code/Derrick/Django/labs/blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title_link %}
<title>Blog</title>
<link rel="stylesheet" href="{% static 'blog/styles.css' %}"><link>
{% endblock title_link %}
    
{% block content %}  
<h1>Welcome to the Blog</h1>

<form action="{% url 'blog:register' %}" method="post">
    <div class="form register">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Register</button>
        <p>Already a member? <a href="{% url 'blog:login' %}">Login here</a></p>
    </div>
</form>
{% endblock content %}